### ISSUE TITLE
Use archive_file resource instead of seven_zip_archive

### ISSUE THREAD

**Issue by webframp** [sensu/sensu-go-chef#110]
Cookstyle gives the following modernization warning

```
resources/ctl.rb:75:5: R: ChefModernize/SevenZipArchiveResource: Use the archive_file resource built into Chef Infra Client 15+ instead of the seven_zip_archive

    seven_zip_archive 'Extract Sensuctl Gz' do

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

resources/ctl.rb:82:5: R: ChefModernize/SevenZipArchiveResource: Use the archive_file resource built into Chef Infra Client 15+ instead of the seven_zip_archive

    seven_zip_archive 'Extract Sensuctl Tar' do

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Since Chef 15+ is already a requirement in our metadata we should fix this.
 
* https://github.com/sensu/sensu-go-chef/blob/master/metadata.rb#L8

**Comment by webframp** [comment]
example failure https://travis-ci.org/github/sensu/sensu-go-chef/jobs/736683770

**Comment by majormoses** [comment]
Wondering if we should have something like maintenance or testing label, I would hardly call that this kind of "issue" a bug.

**Comment by webframp** [comment]
Good idea, I just used the closest thing we had already but happy to use something different

**Comment by majormoses** [comment]
Any preference on names?

**Comment by majormoses** [comment]
I think I am more partial to something broad along the lines of `Type: Maintenance` matching our existing convention.

**Comment by webframp** [comment]
> I think I am more partial to something broad along the lines of `Type: Maintenance` matching our existing convention.

That sounds reasonable to me
