### ISSUE TITLE
Sensu 2.0 filter LWRP

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go-chef#12]
Create a Sensu 2.0 filter LWRP to manage Sensu filters via the Backend API.

Please see #9 for implementation details.

**Comment by webframp** [comment]
@portertech It seems like filters don't behave the same as checks, handlers and assets currently. Is there intentionally a different object schema?

```json
{
  "type": "filter",
  "spec": {
    "name": "production_filter",
    "action": "allow",
    "environment": "default",
    "organization": "default",
    "statements": [
      "event.Entity.Environment == 'production'"
    ]
  }
}
```
```
root@dokken:/# sensuctl create -f /etc/sensu/filters/production_filter.json
error parsing spec: type could not be found: "filter"
Error: some resources couldn't be parsed
```

**Comment by webframp** [comment]
I'm just spelunking, but `filter` was the logical type I could guess. What is the actual type?

From here: https://github.com/sensu/sensu-go/blob/5e9417b9dfc97e502beb375b45b424255fc1b46f/types/filter.pb.go#L83 I'd be led to think it's `EventFilter`

Then I found it: https://github.com/sensu/sensu-go/blob/5e9417b9dfc97e502beb375b45b424255fc1b46f/types/typemap.go#L8
