### ISSUE TITLE
Add example of secret usage on check resource

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-go-chef#139]
We need an example to make it clearer what syntax to use when adding Secrets in Check resources  

Sensu internal ref: https://secure.helpscout.net/conversation/1623979393/26982?folderId=1211665

**Comment by derekgroh** [comment]
Please provide the internal reference you linked directly.

**Comment by agoddard** [comment]
@derekgroh 👋 my apologies for the context for that not being clear - it's a practice we had started in other repos when we have a Sensu customer who initiated the request. The additional info from the customer's request though was that they had intuitively specified:

` secrets ['sensu-aggregate-key': => 'AGGREGATE_USER_KEY'] `

and then realized that the correct usage was: 

`secrets [{ "name": "AGGREGATE_USER_KEY", "secret": 'sensu-aggregate-key'}]`

After which they felt that an example of this usage would be helpful in the docs. If that sounds sensible, I can put together a PR for review w/ this readme change.

**Comment by derekgroh** [comment]
That would be great, we're a bit behind on the documentation with more examples of tests to help ease of use.
