### ISSUE TITLE
Sensu Check `extended_attributes` and adding arbitrary keys

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-go-chef#16]
There is a property called `extended_attributes` with a description of `Coming soon`. I would like clarify the intent of this object as I feel like any non spec specific metadata you would add to a check definition should go here @portertech does that sound right?

I see in this cookbook needing to add `extended_keys` as well as another parameter that accepts a hash with key values to help when new check attributes are released. The idea is to allow someone to start leveraging the functionality before it makes it into the cookbook as a first class property.

Previously in sensu 1.x land we had an `additional` hash that you could pass and I am thinking even if we rename the property to something else (to differentiate the use case from `extended_attributes`) we need to have it. Thoughts?

This was brought up in #14 

@webframp did I miss anything from our previous discussion?

**Comment by webframp** [comment]
This is no longer relevant with the metadata changes recently. According to https://github.com/sensu/sensu-go/blob/master/CHANGELOG.md#breaking-changes "Extended attributes have been removed and replaced with labels. Labels are string-string key-value pairs."

`extended_attributes` property is removed in #38 

See: https://github.com/sensu/sensu-go/pull/2283 

closing, but re-open if further discussion is required
