### ISSUE TITLE
Handlers need an update as there are different types of handlers now

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-go-chef#29]
in 2.x you can set the metrics_handler separately from the handler..so to have a metrics_handler not use any filters you just don't set filters for the listed metrics_handler.

https://github.com/sensu/sensu-docs/issues/522

**Comment by webframp** [comment]
We already have this implemented here:
https://github.com/sensu/sensu-go-chef/blob/master/resources/handler.rb
