### ISSUE TITLE
Create sensu-agent and sensu-backend service LWRPs and consume them in recipes

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go-chef#4]
Create sensu-agent and sensu-backend service LWRPs. The LWRPs need to install the appropriate Sensu 2.x package, manage their respective .yml service configuration files, and manage their service (e.g. systemd start/stop/restart).

**Comment by portertech** [comment]
@majormoses 👍

**Comment by webframp** [comment]
Will start on something for this one today

**Comment by webframp** [comment]
#7 was merged, this could be closed as well?
