### ISSUE TITLE
Add support for installing Sensu Agent MSI on Windows

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go-chef#46]
### Expected Behavior

Cookbook is able to install and configure Sensu Agent MSI on Windows platform

### Actual Behavior

Manual review of this cookbook's source indicates installation on Windows platform is not tested/supported

**Comment by webframp** [comment]
True, it was never implemented. Definitely needed.

**Comment by derekgroh** [comment]
Noted in the PR, but a determination on how to support windows platform testing via travis.ci and what local files to include to support testing need to be discussed.

**Comment by cwjohnston** [comment]
closed by #49 🙌
