### ISSUE TITLE
filters property not working in sensu_asset

### ISSUE THREAD

**Issue by jayme** [sensu/sensu-go-chef#54]
Hello all, 

It seems asset_from_resource in `libraries/helpers.rb` needs:

`spec['filters'] = new_resource.filters if new_resource.filters`

in order to use the filters property in the `sensu_asset` resource.  I can create a pull request if needed.

**Comment by derekgroh** [comment]
This seems to have already been completed: https://github.com/sensu/sensu-go-chef/blob/7b8684a66dea1af3827f6e577c4b6119c17774dc/libraries/helpers.rb#L77
