### ISSUE TITLE
runtime_assets property in sensu_filter resource

### ISSUE THREAD

**Issue by toshit713** [sensu/sensu-go-chef#64]
I appreciate your fantastic job. This cookbook is really good.
However, runtime_assets property in sensu_filter resource cannot be used at ver 0.1.0.
Do you have any plans to address this issue?
I would like to use wonderful filter assets like fatigue-check-filter and has-contact-filter.

**Comment by majormoses** [comment]
@toshit713 that should be pretty easy to add, I have a WIP PR.

**Comment by toshit713** [comment]
Thank you for your quick response and great job!
