### ISSUE TITLE
Add proxy entity resource to readme

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go-chef#73]
Customer explained that they had a bit of a time trying to figure out how to do a proxy check with the cookbook. Could use a useful example of a proxy check.

**Comment by cwjohnston** [comment]
#93 adds an example proxy entity resource but to satisfy this request, we still need an example check which would be scheduled for an agent on behalf of this proxy entity

**Comment by majormoses** [comment]
@cwjohnston can you expand or raise a PR with what you are expecting? I thought that having a valid value for `subscriptions` and specifying the `entity_type` is enough to define a proxy check and get it scheduled. Am I missing anything? https://github.com/sensu/sensu-go-chef/tree/1.1.0#examples-10

**Comment by webframp** [comment]
@majormoses took a shot at trying to explain this in the readme in #113. If it's incorrect or could use more clarity let me

**Comment by majormoses** [comment]
Ah gotcha, @joe-armstrong fyi since you likely need to update some internal cookbooks your migrating.
