### ISSUE TITLE
Add support for SSO providers (AD, LDAP, OIDC)

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go-chef#81]
From what I can currently see, it doesn't seem like we have a resource for enabling LDAP/AD via cookbook. Is this something that can be added? Seems like we'd adopt a similar approach that was done for the postgres config. 

- [x] ActiveDirectory
- [x] LDAP
- [x] OIDC

**Comment by calebhailey** [comment]
Updated the issue title to include all supported SSO providers.

**Comment by webframp** [comment]
Basic support to configure both remaining SSO providers (LDAP, OIDC) is implemented in the referenced PRs. Once those are merged this issue can be closed.

**Comment by webframp** [comment]
Closing, support has been added
