### ISSUE TITLE
Asset resource should support multiple-builds

### ISSUE THREAD

**Issue by tarcinil** [sensu/sensu-go-chef#84]
Upon code review, this cookbook does not appear to use the recommended asset standard for Sensu Go.  The default is defining multiple builds in a single asset.

Is this a good target for a 1.0.0 release?  What are the milestones to get a 1.0.0 release?

### Chef Version

14.x

### Input

N/A

### Output

N/A

### Impact

At present, asset appears to only support single build assets which has been deprecated.  

### Expected Behavior

Windows and Linux assets definitions should be paired together.

### Actual Behavior

They are separate assets based on URL and SHA which are required fields for Sensu Go Chef.

### Steps to Reproduce your problem

N/A - I didn't build anything.

**Comment by derekgroh** [comment]
Could you expand on your expected behavior on Windows and Linux assets definitions being paired together?

**Comment by tarcinil** [comment]
I was referring to this.  https://docs.sensu.io/sensu-go/latest/reference/assets/#asset-definition-multiple-builds
