### ISSUE TITLE
Create Sensu 2.0 object config LWRPs (e.g. check)

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go-chef#9]
Sensu 2.0 object configuration (e.g. check) is done via the Backend API. This cookbook must provide a number of LWRPs for object configuration, one for each Sensu object type. These LWRP must create a Sensu 2.0 object file on disk in a folder named after the object type, e.g. `/etc/sensu/checks`. Each LWRP must support every documented object configuration attribute for their type, e.g. https://docs.sensu.io/sensu-core/2.0/reference/checks/#check-attributes. When the object file is first written to disk or modified, the LWRPs must execute `sensuctl create -f $OBJECT_FILE` in order to create/update the Sensu 2.0 object via the Backend API.

## Object File Examples

/etc/sensu/checks/cron.json
```
{
  "type":"Check",
  "spec":{
    "name":"cron",
    "command":"/bin/true",
    "cron":"* * * * *",
    "subscriptions":[
      "test"
    ],
    "publish":true,
    "handlers":[
      "default"
    ],
    "organization":"default",
    "environment":"default"
  }
}
```

/etc/sensu/handlers/default.json
```
{
  "type":"Handler",
  "spec":{
    "name":"default",
    "type":"set",
    "handlers":[
      "debug"
    ],
    "organization":"default",
    "environment":"default"
  }
}
```

## LWRP Checklist

(Priority ordered)

- [x] check https://github.com/sensu/sensu-go-chef/issues/10
- [x] handler https://github.com/sensu/sensu-go-chef/issues/11
- [x] filter https://github.com/sensu/sensu-go-chef/issues/12
- [x] mutator https://github.com/sensu/sensu-go-chef/issues/13
- [x] hooks  https://github.com/sensu/sensu-go-chef/issues/21

**Comment by webframp** [comment]
Found the filter weirdness and fixed it. PRs for remaining 3 custom resources are all updated. I can rebase as needed.

Once those are reviewed and merged I'll run another pass through testing to make sure there's solid test coverage for all generated specs. 

Then we can discuss next steps and design improvements or refactoring.

**Comment by webframp** [comment]
`sensu_check` is still missing proper `check_hooks` handling, but that should be easy to fix now

**Comment by webframp** [comment]
Just need confirmation on the object schema for creating a check with check_hooks. Tried this without success:
```
{
  "type": "check",
  "spec": {
    "check_hooks": {
      "1": [
        "nginx_restart"
      ]
    },
    "command": "/bin/true",
....
```

**Comment by webframp** [comment]
Found https://github.com/sensu/sensu-docs/issues/401 while working on this issue

**Comment by webframp** [comment]
[ ] hook #21

**Comment by webframp** [comment]
@portertech I think this hook resource is still needed?

**Comment by webframp** [comment]
I think this work has been completed for a little while now.
